steps:
  # Step 1: Access the secret and save it to .env
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Retrieving HEALHIVE_NEXTJS_ENV secret..."
        gcloud secrets versions access latest --secret=HEALHIVE_NEXTJS_ENV > .env
        gcloud secrets versions access latest --secret=SENTRY_AUTH_TOKEN >> .env

  # Step 2: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - "-f"
      - "apps/web/Dockerfile"
      # - "--platform"
      # - "linux/arm64"
      - "-t"
      - "europe-west2-docker.pkg.dev/$_PROJECT/healhive-nextjs/healhive:$SHORT_SHA"
      - "."

  # Step 3: Push the Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - "europe-west2-docker.pkg.dev/$_PROJECT/healhive-nextjs/healhive:$SHORT_SHA"

  # Step 4: Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - "$_SERVICE_NAME"
      - "--image"
      - "europe-west2-docker.pkg.dev/$_PROJECT/healhive-nextjs/healhive:$SHORT_SHA"
      - "--port=3000"
      - "--platform=managed"
      - "--region=$_DEPLOY_REGION"
      - "--allow-unauthenticated"
      - "--revision-suffix=$SHORT_SHA"
      - "--update-env-vars=NEXT_PUBLIC_SENTRY_ENVIRONMENT=$_SENTRY_ENV"

images:
  - "europe-west2-docker.pkg.dev/$_PROJECT/healhive-nextjs/healhive:$SHORT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
