/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'
import { Route as AuthResetPasswordImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterImport } from './routes/_auth/register'
import { Route as AuthLoginImport } from './routes/_auth/login'
import { Route as AppAdminImport } from './routes/_app/admin'
import { Route as AppProfileSetupIndexImport } from './routes/_app/profile-setup/index'
import { Route as AppListsIndexImport } from './routes/_app/lists/index'
import { Route as AppAdminIndexImport } from './routes/_app/admin/index'
import { Route as AppAccountIndexImport } from './routes/_app/account/index'
import { Route as AppListsNewImport } from './routes/_app/lists/new'
import { Route as AppListsListIdImport } from './routes/_app/lists/$listId'
import { Route as AppAccountSettingsImport } from './routes/_app/account/settings'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthResetPasswordRoute = AuthResetPasswordImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const AppAdminRoute = AppAdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

const AppProfileSetupIndexRoute = AppProfileSetupIndexImport.update({
  id: '/profile-setup/',
  path: '/profile-setup/',
  getParentRoute: () => AppRoute,
} as any)

const AppListsIndexRoute = AppListsIndexImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => AppRoute,
} as any)

const AppAdminIndexRoute = AppAdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)

const AppAccountIndexRoute = AppAccountIndexImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AppRoute,
} as any)

const AppListsNewRoute = AppListsNewImport.update({
  id: '/lists/new',
  path: '/lists/new',
  getParentRoute: () => AppRoute,
} as any)

const AppListsListIdRoute = AppListsListIdImport.update({
  id: '/lists/$listId',
  path: '/lists/$listId',
  getParentRoute: () => AppRoute,
} as any)

const AppAccountSettingsRoute = AppAccountSettingsImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminImport
      parentRoute: typeof AppImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof AuthImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordImport
      parentRoute: typeof AuthImport
    }
    '/_app/account/settings': {
      id: '/_app/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AppAccountSettingsImport
      parentRoute: typeof AppImport
    }
    '/_app/lists/$listId': {
      id: '/_app/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof AppListsListIdImport
      parentRoute: typeof AppImport
    }
    '/_app/lists/new': {
      id: '/_app/lists/new'
      path: '/lists/new'
      fullPath: '/lists/new'
      preLoaderRoute: typeof AppListsNewImport
      parentRoute: typeof AppImport
    }
    '/_app/account/': {
      id: '/_app/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexImport
      parentRoute: typeof AppAdminImport
    }
    '/_app/lists/': {
      id: '/_app/lists/'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof AppListsIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/profile-setup/': {
      id: '/_app/profile-setup/'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof AppProfileSetupIndexImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppAdminRouteChildren {
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAccountSettingsRoute: typeof AppAccountSettingsRoute
  AppListsListIdRoute: typeof AppListsListIdRoute
  AppListsNewRoute: typeof AppListsNewRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
  AppListsIndexRoute: typeof AppListsIndexRoute
  AppProfileSetupIndexRoute: typeof AppProfileSetupIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAccountSettingsRoute: AppAccountSettingsRoute,
  AppListsListIdRoute: AppListsListIdRoute,
  AppListsNewRoute: AppListsNewRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
  AppListsIndexRoute: AppListsIndexRoute,
  AppProfileSetupIndexRoute: AppProfileSetupIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/admin': typeof AppAdminRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/account/settings': typeof AppAccountSettingsRoute
  '/lists/$listId': typeof AppListsListIdRoute
  '/lists/new': typeof AppListsNewRoute
  '/account': typeof AppAccountIndexRoute
  '/admin/': typeof AppAdminIndexRoute
  '/lists': typeof AppListsIndexRoute
  '/profile-setup': typeof AppProfileSetupIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/account/settings': typeof AppAccountSettingsRoute
  '/lists/$listId': typeof AppListsListIdRoute
  '/lists/new': typeof AppListsNewRoute
  '/account': typeof AppAccountIndexRoute
  '/admin': typeof AppAdminIndexRoute
  '/lists': typeof AppListsIndexRoute
  '/profile-setup': typeof AppProfileSetupIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_app/account/settings': typeof AppAccountSettingsRoute
  '/_app/lists/$listId': typeof AppListsListIdRoute
  '/_app/lists/new': typeof AppListsNewRoute
  '/_app/account/': typeof AppAccountIndexRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/lists/': typeof AppListsIndexRoute
  '/_app/profile-setup/': typeof AppProfileSetupIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/admin'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/account/settings'
    | '/lists/$listId'
    | '/lists/new'
    | '/account'
    | '/admin/'
    | '/lists'
    | '/profile-setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/register'
    | '/reset-password'
    | '/account/settings'
    | '/lists/$listId'
    | '/lists/new'
    | '/account'
    | '/admin'
    | '/lists'
    | '/profile-setup'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/admin'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_app/account/settings'
    | '/_app/lists/$listId'
    | '/_app/lists/new'
    | '/_app/account/'
    | '/_app/admin/'
    | '/_app/lists/'
    | '/_app/profile-setup/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app",
        "/_auth"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/admin",
        "/_app/account/settings",
        "/_app/lists/$listId",
        "/_app/lists/new",
        "/_app/account/",
        "/_app/lists/",
        "/_app/profile-setup/"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/login",
        "/_auth/register",
        "/_auth/reset-password"
      ]
    },
    "/_app/admin": {
      "filePath": "_app/admin.tsx",
      "parent": "/_app",
      "children": [
        "/_app/admin/"
      ]
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx",
      "parent": "/_auth"
    },
    "/_auth/register": {
      "filePath": "_auth/register.tsx",
      "parent": "/_auth"
    },
    "/_auth/reset-password": {
      "filePath": "_auth/reset-password.tsx",
      "parent": "/_auth"
    },
    "/_app/account/settings": {
      "filePath": "_app/account/settings.tsx",
      "parent": "/_app"
    },
    "/_app/lists/$listId": {
      "filePath": "_app/lists/$listId.tsx",
      "parent": "/_app"
    },
    "/_app/lists/new": {
      "filePath": "_app/lists/new.tsx",
      "parent": "/_app"
    },
    "/_app/account/": {
      "filePath": "_app/account/index.tsx",
      "parent": "/_app"
    },
    "/_app/admin/": {
      "filePath": "_app/admin/index.tsx",
      "parent": "/_app/admin"
    },
    "/_app/lists/": {
      "filePath": "_app/lists/index.tsx",
      "parent": "/_app"
    },
    "/_app/profile-setup/": {
      "filePath": "_app/profile-setup/index.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
