name: movielo-prod
services:
  server:
    container_name: movielo-prod
    image: 'docker.adamhodgkinson.dev/movielo:PROD'
    restart: unless-stopped
    env_file: 'prod.env'
    # environment:
    #   - DATABASE_URL=postgresql://flixxr:password@postgresql:5432/flixxr_db
    #   - PORT=3007
    #   - APP_URL=https://flixxr.xyz
    ports:
      - "3012:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.movielo.rule=Host(`movielo.ahodgk.dev`)"
      - "traefik.http.routers.movielo.entrypoints=websecure"
    networks:
      - proxy
      
networks:
  proxy:
    external: true
