#file: noinspection SpellCheckingInspection
name: Checks
on:
  workflow_call:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
    branches:
    - '*'
  push:
    branches:
    - 'main'
    - 'dev'
    tags-ignore:
      - '*'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn ci-lint

  # test:
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest]
    #     version: [ 22 ]
#        exclude:
#          - os: windows-latest
#            version: 18
#          - os: macos-latest
#            version: 18
#     name: Test
#     services:

# #       Label used to access the service container
#       postgres:
#         # Docker Hub image
#         image: postgres
#         # Provide the password for postgres
#         env:
#           POSTGRES_PASSWORD: postgres
#         # Set health checks to wait until postgres has started
#         options: >-
#           --health-cmd pg_isready
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5
#         ports:
#           # Maps tcp port 5432 on service container to the host
#           - 5498:5432

#     timeout-minutes: 15
#     runs-on:
#       - self-hosted
#       - can-docker-db

#     env:
#       DATABASE_URL: postgres://postgres:postgres@localhost:5498/test_db
# #      DATABASE_URL: ${{secrets.CI_DB_URL }}/ci-${{matrix.os}}-${{matrix.version}}
# #    concurrency:
# #        group: test
# #        cancel-in-progress: false

#     steps:
#       - name: Check out code
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 2

#       - name: Cache turbo build setup
#         uses: actions/cache@v4
#         with:
#           path: .turbo
#           key: ${{ runner.os }}-turbo-${{ github.sha }}
#           restore-keys: |
#             ${{ runner.os }}-turbo-


#       - uses: pnpm/action-setup@v3
#         with:
#           version: 8

#       - name: Setup Node.js environment
#         uses: actions/setup-node@v4
#         with:
#           node-version: 22
#           cache: 'pnpm'

#       - name: Install dependencies
#         run: pnpm install

#       - name: Set .env file
#         run: echo ${{env.DATABASE_URL}} > .env && echo $DATABASE_URL

#       - name: Build
#         run: pnpm build

#       - name: Create database
#         env:
#           DATABASE_URL: ${{env.DATABASE_URL}}
#         run: pnpm db:migrate:reset

#       - name: Test
#         env:
#           DATABASE_URL: ${{env.DATABASE_URL}}
#         run: pnpm test
# #          export DATABASE_URL=${{env.DATABASE_URL}}


